name: CoordiNote
channels:
  - conda-forge
dependencies:
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - click=8.3.1
  - colorama=0.4.6
  - flask=3.1.2
  - icu=78.2
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - krb5=1.21.3
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.2
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libpq=18.2
  - libsqlite=3.51.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - numpy=2.4.2
  - openssl=3.6.1
  - pandas=3.0.0
  - pip=26.0.1
  - psycopg2=2.9.11
  - python=3.14.3
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-tzdata=2025.3
  - python_abi=3.14
  - six=1.17.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - werkzeug=3.1.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - bcrypt==3.2.2
      - cffi==2.0.0
      - passlib==1.7.4
      - pycparser==3.0
prefix: C:\Users\marie\miniforge3\envs\CoordiNote
